### PR TITLE
[filament_view] Fixed texture usage flags for Filament v1.65.2

### PR DESCRIPTION
**Pull request by kerberjg**
Sister PR: https://github.com/meta-flutter/workspace-automation/pull/126

Adds needed usage flag in Texture::Builder

This PR requires the above to be merged, or it won't pass the CI

### CODE REVIEW

**Review by jwinarske — APPROVED** [review]

**Comment by kerberjg** [comment]
@jwinarske CI failure expected as per note above, needs manual merge after https://github.com/meta-flutter/workspace-automation/pull/126

**Comment by jwinarske** [comment]
It needed some changes to compile.  Also addressed compiler warning related to settings.ssao.gato not being set.

**Comment by kerberjg** [comment]
Weird, this should compile just fine with latest Filament:

```
/home/runner/work/ivi-homescreen-plugins/ivi-homescreen-plugins/plugins/plugins/filament_view/core/utils/hdr_loader.cc:49:73: error: no member named 'GEN_MIPMAPPABLE' in  'filament::backend::TextureUsage'
   49 |                        .usage(Texture::Usage::DEFAULT | Texture::Usage::GEN_MIPMAPPABLE)
      |                                                         ~~~~~~~~~~~~~~~~^
```

https://github.com/google/filament/blame/0fa3de5ac7ac28983a5f5d2392bd7d6d2270fac9/filament/backend/include/backend/DriverEnums.h#L1114

**Comment by jwinarske** [comment]
This enum addition in 1.65.2 is a breaking change, so neither 1.60.1 or 1.57 had it; CI was building against both of these.  Updating CI to build with 1.65.2 resolves it.

**Comment by jwinarske** [comment]
This is the last PR to merge for the 1.65.2 roll to work on desktop.  Everything has been tested and running on my end.  meta-vulkan is next.
